# Generated by Django 4.1 on 2022-11-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.TextField(max_length=40)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=200)),
                ('propertyimage', models.TextField(max_length=30)),
                ('available', models.IntegerField()),
            ],
        ),
    ]
