# Generated by Django 4.1 on 2022-11-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hommie', '0002_alter_property_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
