# Generated by Django 4.1 on 2022-11-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hommie', '0003_alter_property_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='contact_landlord',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='contact_owner',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
